"""add unique contrainst for product url per user

Revision ID: 52770bd03ab0
Revises: b3cec113473a
Create Date: 2026-03-19 15:28:40.203215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52770bd03ab0'
down_revision = 'b3cec113473a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_product_url', ['user_id', 'url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_product_url', type_='unique')

    # ### end Alembic commands ###
