"""change price field to numeric

Revision ID: b3cec113473a
Revises: d4556cfd4d31
Create Date: 2026-03-18 13:41:18.277877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cec113473a'
down_revision = 'd4556cfd4d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraped_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('site', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('site')
        batch_op.drop_column('scraped_name')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
